cardshuman/cards/urls.py
from django.contrib import admin
from django.urls import path
from .views import cards
from cards import views
app_name = 'cards'

urlpatterns = [
    path('',views.cards,name='cards'),
]

cardshuman/cardshuman/urls.py
from django.contrib import admin
from django.urls import path,include
from cards import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('card/',include('cards.urls')),
    path('',views.cards,name='cards'),
]

cardshuman/cards/models.py
from django.db import models

# Create your models here.

cardshuman/cards/views.py
from django.shortcuts import render
import random
# Create your views here.

def cards(request):
    import random
    black_cards = [
        "Say it loud! I'm _____ and I'm proud!",
        "I swear to god I'm going to murder my husband if he doesn't shut up about _____.",
        "You wouldn't believe what I found last night! I saw _____.",
        "Check out this dance move of mine! I call it the _____.",
        "Life for minorities were changed forever when they were introduced to _____."
    ]
    white_cards = [
        'Fucking my sister',
        'Molesting the preschoolers',
        'Injecting myself with leukemia',
        'Blowing your dad',
        'A gay fag',
        'A racist',
        'Objectifying my wife',
        'Sodomising my dog',
        'Prostituting my teenage daughter',
        'A girl with cancer',
        'Penis helicopter',
        'Selling my penis on the black market',
        "Your dad's Grindr profile",
        ""
    ]

    black = random.choice(black_cards)
    white = random.choice

cardshuman/cards/templates/cards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CARDS AGAINST THE HUMAN SPECIES</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Cards Against The Human Species</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <span class="navbar-text">
            made by seamus
          </span>
        </div>
      </nav>
    <div class="container">
      {% block content %}{% endblock %}
      </div>
</body>
</html>

cardshuman/cards/templates/cards/index.html
{% extends 'cards/base.html' %}

{% block content %}
    <h1>Welcome to Cards Against the Human Race</h1>
    <div class="card text-white bg-dark mb-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ black }}</h5>
          <p style="opacity: 0.3; user-select: none;">Cards Against The Human Race</p>
        </div>
      </div>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ white }}</h5>
          <p style="opacity: 0.3; user-select: none;">Cards Against The Human Race</p>
        </div>
      </div>
      <br>
      <a class="btn btn-primary" href="{% url 'cards:cards' %}">New combos</a>
{% endblock %}